-- MySQL Script generated by MySQL Workbench
-- Wed Apr 27 10:41:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetojava3e
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetojava3e
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetojava3e` DEFAULT CHARACTER SET utf8 ;
USE `projetojava3e` ;

-- -----------------------------------------------------
-- Table `projetojava3e`.`Atendente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetojava3e`.`Atendente` (
  `matr` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`matr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetojava3e`.`Fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetojava3e`.`Fisica` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `Atendente_matr` INT NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_Fisica_Atendente_idx` (`Atendente_matr` ASC),
  CONSTRAINT `fk_Fisica_Atendente`
    FOREIGN KEY (`Atendente_matr`)
    REFERENCES `projetojava3e`.`Atendente` (`matr`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetojava3e`.`Juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetojava3e`.`Juridica` (
  `cnpj` VARCHAR(6) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `Atendente_matr` INT NOT NULL,
  PRIMARY KEY (`cnpj`),
  INDEX `fk_Juridica_Atendente1_idx` (`Atendente_matr` ASC),
  CONSTRAINT `fk_Juridica_Atendente1`
    FOREIGN KEY (`Atendente_matr`)
    REFERENCES `projetojava3e`.`Atendente` (`matr`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
